### ISSUE TITLE
New field for contributors - emeritus_editorial: true 

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyosMeta#133]
We currently have a field for editorial members on our board that populates the website:

if 
`editorial_board: true`

then they are listed as an editor
now we have added this:

 emeritus_editorial: true

to allow for people who have served with us to still be recognized. we need to add a new field to our contributor pydantic model called  emeritus_editorial that is a bool to support this new website feature. 

```
- name: Ariane Sasso
  github_username: arianesasso
  github_image_id: 3659681
  title: 
    - Emeritus Editor
  emeritus_editorial: true
  editorial_board: false
```

We also will want to add a partners key to the model to ensure partners are recognized. of type list. 

```
- name: Hans Moritz Günther
  github_username: hamogu
  github_image_id: 498688
  title:
  sort:
  bio:
  partners:
    - astropy
 ```

**Comment by lwasser** [comment]
Luiz returns

```
  editorial_board:
  emeritus_editor:
  advisory: false
  twitter:
  mastodon:
  orcidid:
  partners: !!set {}
```

ari
```
- name: Ariane Sasso
  github_username: arianesasso
  github_image_id: 3659681
  title:
    - Emeritus Editor
  sort: 3
  bio: Researcher in Medical Informatics and Digital Health ⌚ 👩‍💻 🧬
  organization: '@hpi-dhc'
  date_added: '2021-08-24'
  deia_advisory: true
  editorial_board: false
  emeritus_editor: true
  advisory: false
  twitter: arianemsasso
  mastodon:
  orcidid:
  partners: !!set {}
```
moritz:
```
- name: Hans Moritz Günther
  github_username: hamogu
  github_image_id: 498688
  title:
  sort: 2
  bio:
  organization: MIT
  date_added: '2023-07-15'
  deia_advisory: false
  editorial_board: true
  emeritus_editor: false
  advisory: false
  twitter:
  mastodon:
  orcidid:
  partners: !!set
      Astropy:

```

Issues

- [ ] luiz should be fixed [by this pr merged now](https://github.com/pyOpenSci/pyopensci.github.io/pull/337)
- [ ] i'm not sure why set is returning oddly in the person model -
